[package]
name = "globed-shared"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
log = { version = "0.4.20" }
serde = { version = "1.0.192", features = ["serde_derive"] }
serde_json = "1.0.108"
time = { version = "0.3.30", features = ["formatting"] }
