[package]
name = "globed-shared"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
crypto_box = { version = "0.9.1", features = ["std", "chacha20"] }
log = { version = "0.4.20" }
nohash-hasher = "0.2.0"
serde = { version = "1.0.193", features = ["serde_derive"] }
serde_json = "1.0.108"
time = { version = "0.3.30", features = ["formatting"] }
