[package]
name = "globed-game-server"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globed-shared = { path = "../shared" }
globed-derive = { path = "../game-derive" }

alloca = "0.4.0"
anyhow = "1.0.75"
array-init = "2.1.0"
bytebuffer = "2.2.0"
parking_lot = "0.12.1"
rand = "0.8.5"
reqwest = "0.11.22"
rustc-hash = "1.1.0"
serde = { version = "1.0.193", features = ["serde_derive"] }
serde_json = "1.0.108"
tokio = { version = "1.35.0", features = ["full"] }

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "globed-bench"
path = "benchmarks/bench.rs"
harness = false

[[test]]
name = "globed-tests"
path = "tests/test.rs"
