[package]
name = "globed-game-server"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globed-shared = { path = "../shared" }
globed-derive = { path = "../derive" }
esp = { path = "../esp" }

alloca = "0.4.0"
parking_lot = "0.12.1"
reqwest = "0.11.22"
rustc-hash = "1.1.0"
tokio = { version = "1.35.0", features = ["full"] }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "globed-bench"
path = "benchmarks/bench.rs"
harness = false

[[test]]
name = "globed-tests"
path = "tests/test.rs"
