[package]
name = "globed-game-server"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bytebuffer = "2.2.0"
colored = "2.0.4"
crypto_box = { version = "0.9.1", features = ["std"] }
log = { version = "0.4.20" }
reqwest = "0.11.22"
rustc-hash = "1.1.0"
time = { version = "0.3.30", features = ["formatting"] }
tokio = { version = "1.33.0", features = ["full"] }
