[package]
name = "globed-game-server"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globed-shared = { path = "../shared" }
globed-derive = { path = "../game-derive" }

alloca = "0.4.0"
anyhow = "1.0.75"
array-init = "2.1.0"
bytebuffer = "2.2.0"
crypto_box = { version = "0.9.1", features = ["std", "chacha20"] }
parking_lot = "0.12.1"
reqwest = "0.11.22"
rustc-hash = "1.1.0"
serde = { version = "1.0.193", features = ["serde_derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
