[package]
name = "globed-central-server"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.6"
digest = "0.10.7"
sodiumoxide = "0.2.7"
totp-rs = { version = "5.4.0", features = ["gen_secret"] }
